# Generated by Django 4.0.2 on 2023-03-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport_object',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
